language: node_js
node_js:
- 9.4.0
script: skip
install: skip
before_deploy:
- npm install -g npm@latest
- npm install -g typescript
- npm install
- npm install gulp
- npm install clone
- npm install gulp-clone
- yarn install
deploy:
  skip_cleanup: true

  provider: npm
  email: info@blackturtle.eu
  api_key:
    secure: xlXZSf0kRF48/LquuYBdVqDIinpS91iTBaZLlBHzLuqwBIKmQfCc9Cz/vbr7iQT/d5oxldbbfm9AtOx+cYjuaVYm/JttD95hOupqEkEn4e4XyjPox8ciAEgTvPLZNPKG3WZhjJUJ3qGUtQrCsiOWul4kQccJqnkWTp+GGXVkc0N2/DXEQ+MvyqrXcJNZpphRp70SRUeIu8bOAd04Xjj0II/7cGyCcCvvSGJu6OpHnGLf8s06KrmGzBbwJXs4iOOcOkhkz68MfKHUPQESfCBYyrxkuZ1GvIqp0qEqCgsXif9UFgbNeYqpEFHVVluxsxfVv8IwONWpWXX39Xz6BEW+01jLZJLpEmY01coWxxQWBmZBC86nNtV2A2bCCkktsBEDFh1cGw/gNkpQVcXwFHeRBYYscc/Op9ePaw6/D5/IrH49hN3+3l0h30ZASfJ9Am+1S3rK1RCjwk2pH9fU4JYPOPfdso/usZ/WZDVJYpew82gaRARFz9/AH1feKssN/ZFvVSmJV0tV7zy2UCHH31dcG32C3EExVu2Fv6QxtdMGw2vEVlnE6TXDSu7RaiIh+Nck6cQSPqPDQ031+sxm0Toj5CIXO8jac8pUx8QGlnZvSYyoDYIT3qVwMhcIvGTyfQjB4jfbuiGyQ7e+ZNRGMB/HZLPuWQOGDISnLGqQNb78acs=
  on:
    repo: BlackTurtle123/tn-signature-adapter
